//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDD_MAIN                        101
#define IDD_CONFIG                      102
#define IDR_MENU1                       102
#define IDD_CFG_WAVEOUT                 103
#define IDI_ICON1                       103
#define IDD_CFG_ASIO                    104
#define IDD_CFG_KS                      105
#define IDD_CONNECT                     106
#define IDD_LICENSE                     107
#define IDD_PREFS                       108
#define IDD_LOCALCHANNEL                110
#define IDD_EMPTY_SCROLL                111
#define IDD_LOCALLIST                   112
#define IDD_REMOTECHANNEL               113
#define IDD_EMPTY                       114
#define IDD_ABOUT                       115
#define IDR_ACCELERATOR1                116
#define IDD_MIXERDLG                    117
#define IDD_MIXERITEM                   118
#define IDD_REMOTEUSER                  119
#define IDD_VSTCFG                      120
#define IDI_ICON2                       121
#define IDD_CONNECT_OLD                 121
#define IDD_SYNC                        122
#define IDC_COMBO1                      1000
#define IDC_MASTERVOL                   1000
#define IDC_CRECT                       1001
#define IDC_COMBO2                      1001
#define IDC_METROVOL                    1001
#define IDC_COMBO3                      1002
#define IDC_MASTERLBL                   1002
#define IDC_MASTERVOLLBL                1002
#define IDC_COMBO4                      1003
#define IDC_RADIO2                      1003
#define IDC_METROLBL                    1003
#define IDC_METROVOLLBL                 1003
#define IDC_COMBO5                      1004
#define IDC_RADIO3                      1004
#define IDC_MASTERPAN                   1004
#define IDC_RADIO4                      1005
#define IDC_METROPAN                    1005
#define IDC_RADIO5                      1006
#define IDC_MASTERVU                    1006
#define IDC_EDIT1                       1007
#define IDC_MASTERVULBL                 1007
#define IDC_EDIT2                       1008
#define IDC_DIV1                        1008
#define IDC_EDIT3                       1009
#define IDC_LATENCYINFO                 1010
#define IDC_INTERVALPOS                 1010
#define IDC_EDIT4                       1011
#define IDC_CHATDIV                     1011
#define IDC_MASTERPANLBL                1011
#define IDC_DIV2                        1012
#define IDC_CHECK1                      1013
#define IDC_MASTERMUTE                  1013
#define IDC_ANON                        1013
#define IDC_SAVEWAVE                    1013
#define IDC_BUTTON1                     1014
#define IDC_METROMUTE                   1014
#define IDC_DIV3                        1015
#define IDC_METROPANLBL                 1016
#define IDC_CHATDISP                    1017
#define IDC_CUSTOM2                     1018
#define IDC_CHATENT                     1018
#define IDC_LOCALSCROLL                 1019
#define IDC_REMOTESCROLL                1020
#define IDC_LOCRECT                     1021
#define IDC_REMOTERECT                  1022
#define IDC_PASSLBL                     1022
#define IDC_PASS                        1023
#define IDC_USER                        1024
#define IDC_HOST                        1025
#define IDC_CHATOK                      1026
#define IDC_LICENSETEXT                 1029
#define IDC_SAVEOGG                     1030
#define IDC_SAVELOCAL                   1031
#define IDC_SAVELOCALWAV                1032
#define IDC_SAVEOGGBR                   1033
#define IDC_SESSIONDIR                  1034
#define IDC_BROWSE                      1035
#define IDC_CHNOTE                      1036
#define IDC_NAME                        1037
#define IDC_TRANSMIT                    1038
#define IDC_MUTE                        1039
#define IDC_SOLO                        1040
#define IDC_REMOVE                      1041
#define IDC_AUDIOIN                     1042
#define IDC_VU                          1043
#define IDC_VULBL                       1044
#define IDC_VU2                         1044
#define IDC_VOL                         1045
#define IDC_PAN                         1046
#define IDC_VOLLBL                      1047
#define IDC_JS                          1048
#define IDC_JSCFG                       1049
#define IDC_ADDCH                       1050
#define IDC_PANLBL                      1050
#define IDC_RECV                        1051
#define IDC_USERNAME                    1053
#define IDC_CHANNELNAME                 1054
#define IDC_LOCGRP                      1054
#define IDC_SESSIONINFO                 1054
#define IDC_REMGRP                      1055
#define IDC_CHATGRP                     1056
#define IDC_VER                         1057
#define IDC_LABEL                       1058
#define IDC_LABEL2                      1060
#define IDC_PASSREMEMBER                1060
#define IDC_DIV                         1062
#define IDC_CHATLBL                     1063
#define IDC_ASYNCXMIT                   1064
#define IDC_EDGE                        1065
#define IDC_LIST1                       1066
#define IDC_CONNECT_LBL                 1067
#define IDC_USERLBL                     1068
#define IDC_INFOTEXT                    1069
#define IDC_MASTER_LBL                  1070
#define IDC_METRO_LBL                   1071
#define IDC_CONNECT                     1072
#define IDC_FLASH                       1073
#define IDC_SETBPM                      1074
#define IDC_SYNCATLOOP                  1075
#define IDC_SYNC                        1076
#define IDC_MATCHBPM_SETLOOP            1077
#define IDC_SETLOOP                     1078
#define ID_LOCAL_CHANNEL_1              2011
#define ID_LOCAL_CHANNEL_2              2012
#define ID_LOCAL_CHANNEL_3              2013
#define ID_LOCAL_CHANNEL_4              2014
#define ID_LOCAL_CHANNEL_5              2015
#define ID_LOCAL_CHANNEL_6              2016
#define ID_LOCAL_CHANNEL_7              2017
#define ID_LOCAL_CHANNEL_8              2018
#define ID_LOCAL_CHANNEL_9              2019
#define ID_LOCAL_CHANNEL_10             2020
#define ID_LOCAL_CHANNEL_50             2060
#define ID_REMOTE_USER_1                2061
#define ID_REMOTE_USER_2                2062
#define ID_REMOTE_USER_3                2063
#define ID_REMOTE_USER_4                2064
#define ID_REMOTE_USER_5                2065
#define ID_REMOTE_USER_6                2066
#define ID_REMOTE_USER_7                2067
#define ID_REMOTE_USER_8                2068
#define ID_REMOTE_USER_9                2069
#define ID_REMOTE_USER_10               2070
#define ID_REMOTE_USER_50               2110
#define ID_REMOTE_USER_CHANNEL_1        2111
#define ID_REMOTE_USER_CHANNEL_2        2112
#define ID_REMOTE_USER_CHANNEL_3        2113
#define ID_REMOTE_USER_CHANNEL_4        2114
#define ID_REMOTE_USER_CHANNEL_5        2115
#define ID_REMOTE_USER_CHANNEL_6        2116
#define ID_REMOTE_USER_CHANNEL_7        2117
#define ID_REMOTE_USER_CHANNEL_8        2118
#define ID_REMOTE_USER_CHANNEL_9        2119
#define ID_REMOTE_USER_CHANNEL_10       2120
#define ID_REMOTE_USER_CHANNEL_50       2160
#define ID_METRONOME_CH5                2161
#define ID_LOCAL_CH34                   2162
#define ID_FILE_CONNECT                 40001
#define ID_FILE_DISCONNECT              40002
#define ID_FILE_QUIT                    40003
#define ID_HELP_ABOUTNINJAM             40004
#define ID_OPTIONS_PREFERENCES          40005
#define ID_OPTIONS_ALWAYSONTOP          40006
#define ID_OPTIONS_AUDIOCONFIGURATION   40007
#define ID_LOW_LAT                      40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
