//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ninjam.rc
//
#define IDD_PANEL_CHANNEL               101
#define IDI_NINJAM                      102
#define IDD_PANEL_GROUP                 103
#define IDD_DIALOG1                     104
#define IDD_PANEL_LOCALCHANNEL          104
#define IDD_DIALOG2                     105
#define IDD_PANEL_MASTER                105
#define IDD_PANEL_SERVER                106
#define IDD_SERVER                      106
#define IDD_USERPASS                    107
#define IDD_CONFIG                      108
#define IDD_CFG_ASIO                    109
#define IDD_PANEL_METRONOME             110
#define IDD_PANEL_SWEEP                 111
#define IDD_CONFIG_RECORD               112
#define IDD_CONFIG_MAIN                 112
#define IDD_PANEL_JESUS                 113
#define IDD_SERVER_LICENSE              114
#define IDD_CHAT                        115
#define IDD_CFG_KS                      116
#define IDD_CFG_WAVEOUT                 117
#define IDI_ICON1                       118
#define IDD_CLOSESESSION                119
#define IDD_PANEL_SEPARATOR             120
#define IDD_PANEL_CHAN_SEPARATOR        120
#define IDD_PANEL_LOCAL_SEPARATOR       121
#define IDD_ABOUT                       122
#define IDD_PANEL_AUDIO                 123
#define IDD_MIDICLOCK_DEVICE            124
#define IDC_BUTTON1                     1000
#define IDC_PANEL_SOLO                  1000
#define IDC_BUTTON2                     1001
#define IDC_PANEL_MUTE                  1001
#define IDC_SESSIONDIR_BROWSE           1001
#define IDC_DELMULTI                    1001
#define IDC_MIDICLOCK_STOP              1001
#define IDC_BUTTON5                     1002
#define IDC_DELOGG                      1002
#define IDC_SLIDER1                     1003
#define IDC_SLIDER2                     1004
#define IDC_GROUPBOX                    1007
#define IDC_BUTTON4                     1009
#define IDC_CHANNEL_NAME                1010
#define IDC_CHANNEL_USER                1011
#define IDC_PAN                         1012
#define IDC_VOLUME                      1013
#define IDC_SOLO                        1015
#define IDC_MUTE                        1016
#define IDC_SUB                         1017
#define IDC_CHANNEL_SUBSCRIBED          1017
#define IDC_EDIT1                       1018
#define IDC_SERVER_LICENSE_TEXT         1018
#define IDC_JESUSDIR                    1018
#define IDC_BUTTON3                     1019
#define IDC_EDIT4                       1019
#define IDC_CONFIGUREAUDIO              1019
#define IDC_CUSTOM1                     1020
#define IDC_EDIT5                       1020
#define IDC_PASSWD                      1021
#define IDC_USERNAME                    1022
#define IDC_SERVER                      1023
#define IDC_COMBO1                      1024
#define IDC_CRECT                       1025
#define IDC_COMBO2                      1026
#define IDC_COMBO3                      1027
#define IDC_COMBO4                      1028
#define IDC_COMBO5                      1029
#define IDC_REMEMBER_PASSWD             1029
#define IDC_METRONOME_VOLUME            1030
#define IDC_METRONOME_FRAME             1031
#define IDC_METRONOME_PAN               1032
#define IDC_CHANNEL_ID                  1033
#define IDC_ANONYMOUS                   1034
#define IDC_SWEEP                       1035
#define IDC_BROADCAST                   1037
#define IDC_TICKMARK                    1039
#define IDC_MONITOR                     1040
#define IDC_VOLUME_TEXT                 1041
#define IDC_PAN_TEXT                    1042
#define IDC_CHECK1                      1043
#define IDC_WRITE_LOG                   1043
#define IDC_CHECK2                      1044
#define IDC_WRITE_WAV                   1044
#define IDC_KEEPOGG                     1044
#define IDC_VU                          1045
#define IDC_SUBSCRIBE                   1046
#define IDC_LOCAL_TEXT                  1047
#define IDC_VUMETER                     1048
#define IDC_LOCAL_SRCCHAN               1049
#define IDC_SERVER_LICENSE_AGREE        1050
#define IDC_EDIT2                       1051
#define IDC_SESSIONDIR                  1051
#define IDC_CHECK3                      1052
#define IDC_KEEPLOG                     1052
#define IDC_CHECK4                      1053
#define IDC_AUDIOENABLE                 1053
#define IDC_CHAT_HIST                   1055
#define IDC_CHAT_DISP                   1055
#define IDC_CHAT_EDIT                   1056
#define IDC_CHAT_ENTRY                  1056
#define IDC_CHAT_ENTER                  1057
#define IDC_FX                          1058
#define IDC_EDIT_FX                     1059
#define IDC_SHOWATSTART                 1060
#define IDC_LOCAL_CHID                  1061
#define IDC_JS_BROWSE                   1062
#define IDC_WRITE_OGG                   1063
#define IDC_OGG_BITRATE                 1064
#define IDC_RADIO3                      1065
#define IDC_RADIO4                      1066
#define IDC_RADIO5                      1067
#define IDC_EDIT3                       1068
#define IDC_LATENCYINFO                 1069
#define IDC_EXAMPLEDIR                  1071
#define IDC_SESSION_FORMAT              1072
#define IDC_VUCLIP                      1073
#define IDC_KEEPWAV                     1074
#define IDC_SESSION_NAME                1075
#define IDC_SESSION_LEN                 1077
#define IDC_SEPTEXT                     1078
#define IDC_CHAT_TOPIC                  1079
#define IDC_VOLTEXT                     1080
#define IDC_VUTEXT                      1081
#define IDC_SESSION_POS                 1083
#define IDC_VERSION_TEXT                1084
#define IDC_SRCCHAN                     1087
#define IDC_DELWAV                      1088
#define IDC_MIDICLOCK                   1089
#define IDC_MIDICLOCK_ENABLE            1090
#define IDC_MIDICLOCK_START             1091
#define IDC_MIDIOUT_LIST                1092

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
