//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by winclientres.rc
//
#define IDD_MAIN                        101
#define IDD_CONFIG                      102
#define IDR_MENU1                       102
#define IDD_CFG_WAVEOUT                 103
#define IDI_ICON1                       103
#define IDD_CFG_ASIO                    104
#define IDD_CFG_KS                      105
#define IDD_CONNECT                     106
#define IDD_LICENSE                     107
#define IDD_PREFS                       108
#define IDD_LOCALCHANNEL                110
#define IDD_EMPTY_SCROLL                111
#define IDD_LOCALLIST                   112
#define IDD_REMOTECHANNEL               113
#define IDD_EMPTY                       114
#define IDD_ABOUT                       115
#define IDR_ACCELERATOR1                116
#define IDD_MIXERDLG                    117
#define IDD_MIXERITEM                   118
#define IDC_COMBO1                      1000
#define IDC_MASTERVOL                   1000
#define IDC_CRECT                       1001
#define IDC_COMBO2                      1001
#define IDC_METROVOL                    1001
#define IDC_COMBO3                      1002
#define IDC_MASTERLBL                   1002
#define IDC_MASTERVOLLBL                1002
#define IDC_COMBO4                      1003
#define IDC_RADIO2                      1003
#define IDC_METROLBL                    1003
#define IDC_METROVOLLBL                 1003
#define IDC_COMBO5                      1004
#define IDC_RADIO3                      1004
#define IDC_MASTERPAN                   1004
#define IDC_RADIO4                      1005
#define IDC_METROPAN                    1005
#define IDC_RADIO5                      1006
#define IDC_MASTERVU                    1006
#define IDC_EDIT1                       1007
#define IDC_MASTERVULBL                 1007
#define IDC_EDIT2                       1008
#define IDC_DIV1                        1008
#define IDC_EDIT3                       1009
#define IDC_STATUS                      1009
#define IDC_LATENCYINFO                 1010
#define IDC_INTERVALPOS                 1010
#define IDC_EDIT4                       1011
#define IDC_CHATDIV                     1011
#define IDC_MASTERPANLBL                1011
#define IDC_DIV2                        1012
#define IDC_CHECK1                      1013
#define IDC_MASTERMUTE                  1013
#define IDC_ANON                        1013
#define IDC_SAVEWAVE                    1013
#define IDC_BUTTON1                     1014
#define IDC_METROMUTE                   1014
#define IDC_DIV3                        1015
#define IDC_METROPANLBL                 1016
#define IDC_CHATDISP                    1017
#define IDC_CUSTOM2                     1018
#define IDC_CHATENT                     1018
#define IDC_LOCALSCROLL                 1019
#define IDC_REMOTESCROLL                1020
#define IDC_LOCRECT                     1021
#define IDC_REMOTERECT                  1022
#define IDC_PASSLBL                     1022
#define IDC_PASS                        1023
#define IDC_USER                        1024
#define IDC_HOST                        1025
#define IDC_CHATOK                      1026
#define IDC_STATUS2                     1028
#define IDC_LICENSETEXT                 1029
#define IDC_SAVEOGG                     1030
#define IDC_SAVELOCAL                   1031
#define IDC_SAVELOCALWAV                1032
#define IDC_SAVEOGGBR                   1033
#define IDC_SESSIONDIR                  1034
#define IDC_BROWSE                      1035
#define IDC_CHNOTE                      1036
#define IDC_NAME                        1037
#define IDC_TRANSMIT                    1038
#define IDC_MUTE                        1039
#define IDC_SOLO                        1040
#define IDC_REMOVE                      1041
#define IDC_AUDIOIN                     1042
#define IDC_VU                          1043
#define IDC_VULBL                       1044
#define IDC_VOL                         1045
#define IDC_PAN                         1046
#define IDC_VOLLBL                      1047
#define IDC_JS                          1048
#define IDC_JSCFG                       1049
#define IDC_ADDCH                       1050
#define IDC_RECV                        1051
#define IDC_USERNAME                    1053
#define IDC_CHANNELNAME                 1054
#define IDC_LOCGRP                      1054
#define IDC_REMGRP                      1055
#define IDC_CHATGRP                     1056
#define IDC_VER                         1057
#define IDC_LABEL                       1058
#define IDC_LABEL2                      1060
#define ID_FILE_CONNECT                 40001
#define ID_FILE_DISCONNECT              40002
#define ID_FILE_QUIT                    40003
#define ID_HELP_ABOUTNINJAM             40004
#define ID_OPTIONS_PREFERENCES          40005
#define ID_OPTIONS_ALWAYSONTOP          40006
#define ID_OPTIONS_AUDIOCONFIGURATION   40007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
